!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2_7353)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2py_bvp_getdims_parameters(r,s,f2pysetdata,flag)
      use bvp, only: d => parameters

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(4) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_bvp_getdims_parameters
      subroutine f2py_bvp_getdims_work(r,s,f2pysetdata,flag)
      use bvp, only: d => work

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(4) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_bvp_getdims_work
      subroutine f2py_bvp_getdims_evaluated(r,s,f2pysetdata,flag)
      use bvp, only: d => evaluated

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(4) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_bvp_getdims_evaluated
      subroutine f2py_bvp_getdims_evaluated_d(r,s,f2pysetdata,flag)
      use bvp, only: d => evaluated_d

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(4) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_bvp_getdims_evaluated_d
      subroutine f2py_bvp_getdims_x(r,s,f2pysetdata,flag)
      use bvp, only: d => x

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(4) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_bvp_getdims_x
      subroutine f2py_bvp_getdims_iwork(r,s,f2pysetdata,flag)
      use bvp, only: d => iwork

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(4) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_bvp_getdims_iwork
      subroutine f2py_bvp_getdims_y(r,s,f2pysetdata,flag)
      use bvp, only: d => y

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(4) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_bvp_getdims_y
      
      subroutine f2pyinitbvp(f2pysetupfunc)
      use bvp, only : node
      use bvp, only : info
      use bvp, only : mxnsub
      use bvp, only : parameters
      use bvp, only : work
      use bvp, only : evaluated
      use bvp, only : evaluated_d
      use bvp, only : x
      use bvp, only : iwork
      use bvp, only : yerror
      use bvp, only : y
      use bvp, only : npts
      use bvp, only : npar
      use bvp, only : leftbc
      use bvp, only : guess_1_wrap
      use bvp, only : guess_2_wrap
      use bvp, only : guess_3_wrap
      use bvp, only : bvp_solver_wrap
      use bvp, only : bvp_eval_wrap
      use bvp, only : bvp_extend_wrap
      external f2pysetupfunc
      external f2py_bvp_getdims_parameters
      external f2py_bvp_getdims_work
      external f2py_bvp_getdims_evaluated
      external f2py_bvp_getdims_evaluated_d
      external f2py_bvp_getdims_x
      external f2py_bvp_getdims_iwork
      external f2py_bvp_getdims_y
      call f2pysetupfunc(node,info,mxnsub,f2py_bvp_getdims_parameters,f2&
     &py_bvp_getdims_work,f2py_bvp_getdims_evaluated,f2py_bvp_getdims_ev&
     &aluated_d,f2py_bvp_getdims_x,f2py_bvp_getdims_iwork,yerror,f2py_bv&
     &p_getdims_y,npts,npar,leftbc,guess_1_wrap,guess_2_wrap,guess_3_wra&
     &p,bvp_solver_wrap,bvp_eval_wrap,bvp_extend_wrap)
      end subroutine f2pyinitbvp


